/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-project`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/demo/hello-styles`; params?: Router.UnknownInputParams; } | { pathname: `/demo/hello-world`; params?: Router.UnknownInputParams; } | { pathname: `/project/[id]/active`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/new-project`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/demo` | `/demo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/demo/hello-styles`; params?: Router.UnknownOutputParams; } | { pathname: `/demo/hello-world`; params?: Router.UnknownOutputParams; } | { pathname: `/project/[id]/active`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/project/[id]/details`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/new-project${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/demo${`?${string}` | `#${string}` | ''}` | `/demo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/demo/hello-styles${`?${string}` | `#${string}` | ''}` | `/demo/hello-world${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-project`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/demo` | `/demo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/demo/hello-styles`; params?: Router.UnknownInputParams; } | { pathname: `/demo/hello-world`; params?: Router.UnknownInputParams; } | `/project/${Router.SingleRoutePart<T>}/active${`?${string}` | `#${string}` | ''}` | `/project/${Router.SingleRoutePart<T>}/details${`?${string}` | `#${string}` | ''}` | { pathname: `/project/[id]/active`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/project/[id]/details`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
